# Generated by Django 2.2.1 on 2019-05-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='date',
        ),
    ]
